openapi: 3.0.1
info:
  title: monster-nymph
  x-cortex-tag: monster-nymph
  x-cortex-custom-metadata:
    alignment: lawful-evil
    type: fiend
    challenge_rating: 25
    legendary: false
    armor_class: 14
    hit_points: 66
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-nymph
      alias: github-token-test
